export const words = [
  "PYTHON", "JAVASCRIPT", "TYPESCRIPT", "REACT", "ANGULAR", "SVELTE", "NEXTJS", "NODEJS",
  "MONGODB", "POSTGRES", "MYSQL", "REDIS", "DOCKER", "KUBERNETES", "LINUX", "WINDOWS",
  "ANDROID", "FLUTTER", "SWIFT", "KOTLIN", "JAVA", "SCALA", "RUST", "GOLANG",
  "AZURE", "AMAZON", "GOOGLE", "GITHUB", "GITLAB", "BITBUCKET", "JENKINS", "TRAVIS",
  "AGILE", "SCRUM", "KANBAN", "JIRA", "CONFLUENCE", "SLACK", "DISCORD", "TEAMS",
  "FRONTEND", "BACKEND", "FULLSTACK", "DEVOPS", "SECURITY", "TESTING", "DESIGN", "MOBILE",
  // ... more words can be added here
];